version: '3.8'

services:
  agent47-app:
    build: .
    container_name: agent47_app
    restart: always
    ports:
      - "${HOST_PORT:-8080}:8000"
    volumes:
      - ./database:/app/database
    env_file:
      - .env
    environment:
      - PORT=8000
